### PR TITLE
Hope for your accept 

### PR DESCRIPTION
**Pull request by IhorNehrutsa**
I will use git-flow in future
https://danielkummer.github.io/git-flow-cheatsheet/index.html
to prevent pushing to the master branch.

### CODE REVIEW

**Comment by pazzarpj** [comment]
Hey Ihor,
This PR has changes from your previous PR included.
Are you able to sync your changes to upstream master before raising the PR so it will only contain new changes?

**Comment by IhorNehrutsa** [comment]
Hi Ryan.
Thanks for your hint.
I synchronized 'master' branches. 
Now two commits are in PR:

_Put Python module description to C code_
and
_Remove unnecessary '(' for zero number of function parameters._

Is that well now?
Sorry for my noob.

**Comment by pazzarpj** [comment]
It's all good Ihor don't worry about coming across as a github noob. I'm still there myself.

I have added some github actions to run tests against any new code. 
I don't have any tests for the stub_module and apparently no tests for zero arguments.

I will raise individual issues for what you are proposing as changes so we can write some tests to confirm the changes.

If possible do you have input/output examples that demonstrate the behavior you are trying to fix?

**Comment by pazzarpj** [comment]
Added issues #16 #17 to match the PR

**Comment by pazzarpj** [comment]
Closing pull request. Have individual PRs for the two issues resolved in this PR

**Pull request closed without merging**
